# Generated by Django 5.0.4 on 2024-05-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام دسته بندی')),
                ('image', models.ImageField(upload_to='product_category/', verbose_name='عکس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی های محصولات',
                'db_table': 'product_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام کالا')),
                ('image', models.ImageField(upload_to='products/', verbose_name='عکس کالا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت محصول')),
                ('buy_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.productcategorymodel', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
    ]
