# Generated by Django 5.0.4 on 2024-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
