# Generated by Django 5.0.4 on 2024-06-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='Product_Module.productmodel', verbose_name='کالا'),
        ),
    ]
