# Generated by Django 5.0.4 on 2024-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0005_productmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
