# Generated by Django 5.0.4 on 2024-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0009_antennamodel_batterymodel_buildingequipmentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightandbrightnessmodel',
            name='category',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('about_us', 'درباره ما')], default='', max_length=200, verbose_name='جایگاه نمایشی'),
            preserve_default=False,
        ),
    ]
