# Generated by Django 5.0.4 on 2024-06-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0010_lightandbrightnessmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntennaModel',
        ),
        migrations.DeleteModel(
            name='BatteryModel',
        ),
        migrations.DeleteModel(
            name='BuildingEquipmentModel',
        ),
        migrations.DeleteModel(
            name='ControlModel',
        ),
        migrations.DeleteModel(
            name='EntryPhoneModel',
        ),
        migrations.DeleteModel(
            name='LightAndBrightnessModel',
        ),
        migrations.DeleteModel(
            name='MiscellaneousGoodsModel',
        ),
        migrations.DeleteModel(
            name='ProtectorAndTeeModel',
        ),
        migrations.DeleteModel(
            name='SwitchesAndSocketsModel',
        ),
        migrations.DeleteModel(
            name='WireAndCableModel',
        ),
    ]
