# Generated by Django 5.0.4 on 2024-06-26 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0011_delete_antennamodel_delete_batterymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightAndBrightnessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام کالا')),
                ('image', models.ImageField(upload_to='products/', verbose_name='عکس کالا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت محصول')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت پس از تخفیف')),
                ('offer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('buy_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد در انبار')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('about_us', 'درباره ما')], max_length=200, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
