# Generated by Django 5.0.4 on 2024-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0012_lightandbrightnessmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LightAndBrightnessModel',
        ),
    ]
