# Generated by Django 5.0.4 on 2024-06-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingmodel',
            name='description_img',
        ),
    ]
