# Generated by Django 5.0.4 on 2024-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0002_remove_sitesettingmodel_description_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام بنر')),
                ('image', models.ImageField(upload_to='banners', verbose_name='عکس بنر')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنر های سایت',
                'db_table': 'banner_site',
            },
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='banners',
            field=models.ManyToManyField(to='Site_Module.bannersitemodel', verbose_name='بنر های سایت'),
        ),
    ]
